const sampledata = [
  {
    id: 1,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 2,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 3,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 4,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 5,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 6,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 7,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 8,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 9,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 10,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
  {
    id: 11,
    image: "",
    title: "Card Title",
    time: "Now",
    location: "location",
    desc: "omething about the products and some description.....",
    brand: "Brand",
  },
];

export default sampledata;
